services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/Lupita-a1112we/Ejem_ESP32.git
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://lupitajacinto1012:Lupi12345@cluster0.cxpd12p.mongodb.net/?retryWrites=true&w=majority
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
